package com.inquiro.searchengine.model;

import jakarta.persistence.*;
import java.util.Objects;

// JPA entity to be mapped to a database table
@Entity
// Specifies the name of the table in the database as "search_results"
@Table(name = "search_results")
public class SearchResult {

    // Primary key, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String keyword;
    private String title;
    private String url;
    private String description;

    // required constructor 
    public SearchResult() {}

    // SearchResult object, all fields except 'id'
    public SearchResult(String keyword, String title, String url, String description) {
        this.keyword = keyword;
        this.title = title;
        this.url = url;
        this.description = description;
    }

    // Getters
    public Long getId() {
        return id;
    }

    public String getKeyword() {
        return keyword;
    }

    public String getTitle() {
        return title;
    }

    public String getUrl() {
        return url;
    }

    public String getDescription() {
        return description;
    }

    // Setters
    public void setId(Long id) {
        this.id = id;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // Override equals() and hashCode() Set behavior for AND search
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SearchResult)) return false;
        SearchResult that = (SearchResult) o;
        return url != null && url.equalsIgnoreCase(that.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(url != null ? url.toLowerCase() : null);
    }
}
